name: mofit_app
description: Mo-fit تطبيق تتبع حساب السعرات الحراريه واللياقه البدنيه
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  firebase_database: ^11.1.0
  firebase_storage: ^12.1.0
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

  # إضافات الواجهة
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shared_preferences: ^2.3.2

  # خطوات + GPS
  pedometer: ^4.0.2
  permission_handler: ^11.3.1
  geolocator: ^11.0.0

  # صور + روابط
  image_picker: ^1.1.2
  url_launcher: ^6.3.1

  # intl للتواريخ
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
