// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb_LODFIFpYxtPp_M_wITyVm2Bgo_Pu4Q',
    appId: '1:288877347850:web:fc89d0df60827e9605cbf3',
    messagingSenderId: '288877347850',
    projectId: 'mo-fit-d0762',
    authDomain: 'mo-fit-d0762.firebaseapp.com',
    storageBucket: 'mo-fit-d0762.firebasestorage.app',
    measurementId: 'G-C6R0W69S80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAjBAp2DfswmiIbkOD9QrnXQ20k3W-yeo',
    appId: '1:288877347850:android:0d7d0df6017f5f8305cbf3',
    messagingSenderId: '288877347850',
    projectId: 'mo-fit-d0762',
    storageBucket: 'mo-fit-d0762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfLHP1yfEmyPl-NQIF4CSJs9nU9VDGNdk',
    appId: '1:288877347850:ios:a86c78decff64a7005cbf3',
    messagingSenderId: '288877347850',
    projectId: 'mo-fit-d0762',
    storageBucket: 'mo-fit-d0762.firebasestorage.app',
    androidClientId: '288877347850-ord4p0kkdtak72tha2kl330ul07576vv.apps.googleusercontent.com',
    iosClientId: '288877347850-cqq5a1f17c7hm43n2pa65fk435p9bbij.apps.googleusercontent.com',
    iosBundleId: 'com.example.mofitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfLHP1yfEmyPl-NQIF4CSJs9nU9VDGNdk',
    appId: '1:288877347850:ios:a86c78decff64a7005cbf3',
    messagingSenderId: '288877347850',
    projectId: 'mo-fit-d0762',
    storageBucket: 'mo-fit-d0762.firebasestorage.app',
    androidClientId: '288877347850-ord4p0kkdtak72tha2kl330ul07576vv.apps.googleusercontent.com',
    iosClientId: '288877347850-cqq5a1f17c7hm43n2pa65fk435p9bbij.apps.googleusercontent.com',
    iosBundleId: 'com.example.mofitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb_LODFIFpYxtPp_M_wITyVm2Bgo_Pu4Q',
    appId: '1:288877347850:web:30bb610978b1b13005cbf3',
    messagingSenderId: '288877347850',
    projectId: 'mo-fit-d0762',
    authDomain: 'mo-fit-d0762.firebaseapp.com',
    storageBucket: 'mo-fit-d0762.firebasestorage.app',
    measurementId: 'G-GJ591JCL2E',
  );

}